from database.race_results_operations import get_drivers_per_year_from_races, get_race_result_data_race_year, get_driver_results_per_year, get_driver_points_per_season_with_race_results
from utils.race_weekends_order import race_orders, unique_races

from utils.sprint_weekends_order import sprint_orders, unique_sprints
from database.sprints_operations import get_drivers_per_year_from_sprints, get_sprint_result_data_sprint_year, get_driver_results_per_year_sprints, get_driver_points_per_season_with_sprint_results

from database.qualifications_operations import get_drivers_per_year_from_qualifications, get_qualifications_data_race_year, get_driver_results_per_year_qualifications

from database.sprint_qualifications_operations import get_drivers_per_year_from_sprint_qualifications, get_sprint_qualifications_data_sprint_year, get_driver_results_per_year_sprint_qualifications

from database.practice_1_operations import get_drivers_per_year_from_practice1_data, get_practice1_data_data_race_year, get_driver_results_per_year_practice1_data
from utils.practice_1_order import practice1_orders, unique_practice1
from database.practice_2_operations import get_drivers_per_year_from_practice2_data, get_practice2_data_data_race_year, get_driver_results_per_year_practice2_data
from utils.practice_2_order import practice2_orders, unique_practice2
from database.practice_3_operations import get_drivers_per_year_from_practice3_data, get_practice3_data_data_race_year, get_driver_results_per_year_practice3_data
from utils.practice_3_order import practice3_orders, unique_practice3

from database.standings_operations import merge_race_and_sprint_data

from utils.highlights import get_highlights_for_specified_year_race_and_session, get_sessions_per_year_and_race

from plots.time_deltas_operations import plot_time_gap_per_session, plot_time_gap_practice_session, calculate_time_delta